# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: One
  steps:
  -task: Maven@1
   inputs:
   mavenOptions: '-Xmx3072m'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '1.7'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: false
   testResultsFiles: '**/TEST-*.xml'
   goals: 'install:install-file -D./LibsManager/libs/jar-in-jar-loader-1.1.jar -DgroupId=org.eclipse.jdt.internal -DartifactId=ar-in-jar-loader -Dversion=1.1 -Dpackaging=jar'

-job: Two
 steps:
 - task: Maven@3
   inputs:
   mavenPomFile: 'ParentPom/pom.xml'
   mavenOptions: '-Xmx3072m'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '1.7'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: false
   testResultsFiles: '**/TEST-*.xml'
   #goals: 'package'
   #goals: 'clean install'
   goals: '-X install'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
